across:
  development:
    active: true

applicationInfo:
  environmentId: development

server:
  error:
    includeStacktrace: ALWAYS
  port: 8080


spring:
  datasource:
    url: "jdbc:h2:./local-data/db/booking-db"
    username: sa

