across:
  development:
    active: true

acrossHibernate:
  hibernate-properties:
    hibernate.format_sql: false
    hibernate.use_sql_comments: false
    hibernate.show_sql: false

server:
  error:
    includeStacktrace: ALWAYS
  port: 8099

spring:
  datasource:
    url: "jdbc:h2:./local-data/db/musical-api-db"
    username: sa

